/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */

const fs = require('fs');
const express = require('express');
const app = express();


const flightData = [
  {
    id: 1,
    current_city: "Vancouver",
    destination_city: "Barcelona",
    time: "10:00am-4:50pm",
    date: "December 2, 2023",
    airline: "Air Canada",
    price: "$850",
    iata: "BCN",
},  
{
  id: 2,
  current_city: "Vancouver",
  destination_city: "Barcelona",
  time: "12:00pm-8:10pm",
  date: "December 2, 2023",
  airline: "West Jet",
  price: "$930",
  iata: "BCN",
},
{
  id: 3,
  current_city: "Vancouver",
  destination_city: "Barcelona",
  time: "1:30pm-9:45pm",
  date: "December 3, 2023",
  airline: "Swoop",
  price: "$825",
  iata: "BCN",
},
{
  id: 4,
  current_city: "Vancouver",
  destination_city: "Barcelona",
  time: "7:30pm-3:45am",
  date: "December 4, 2023",
  airline: "Lufthansa",
  price: "$1050",
  iata: "BCN",
},
{
  id: 5,
  current_city: "Vancouver",
  destination_city: "London",
  time: "10:30am-7:15pm",
  date: "December 10, 2023",
  airline: "British Airlines",
  price: "$1230",
  iata: "LON",
},
{
  id: 6,
  current_city: "Vancouver",
  destination_city: "London",
  time: "10:45am-7:30pm",
  date: "December 11, 2023",
  airline: "West Jet",
  price: "$1345",
  iata: "LON",
},
{
  id: 7,
  current_city: "Vancouver",
  destination_city: "London",
  time: "2:30pm-11:10pm",
  date: "December 12, 2023",
  airline: "Air Canada",
  price: "$1450",
  iata: "LON",
},
{
  id: 8,
  current_city: "Vancouver",
  destination_city: "London",
  time: "9:30pm-5:10pm",
  date: "December 14, 2023",
  airline: "British Airways",
  price: "$1580",
  iata: "LON",
},
{
  id: 9,
  current_city: "Vancouver",
  destination_city: "New York",
  time: "7:30am-12:10pm",
  date: "December 8, 2023",
  airline: "Air Canada",
  price: "$800",
  iata: "JFK",
},
{
  id: 10,
  current_city: "Vancouver",
  destination_city: "New York",
  time: "2:30pm-7:35pm",
  date: "December 12, 2023",
  airline: "Air Canada",
  price: "$820",
  iata: "JFK",
},
{
  id: 11,
  current_city: "Vancouver",
  destination_city: "New York",
  time: "10:30pm-3:00am",
  date: "December 13, 2023",
  airline: "American Airlines",
  price: "$770",
  iata: "LGA",
},
{
  id: 12,
  current_city: "Vancouver",
  destination_city: "New York",
  time: "1:00am-6:00am",
  date: "December 15, 2023",
  airline: "American Airlines",
  price: "$900",
  iata: "JFK",
},
{
  id: 13,
  current_city: "Vancouver",
  destination_city: "Los Angeles",
  time: "9:30am-1:35pm",
  date: "December 13, 2023",
  airline: "American Airlines",
  price: "$450",
  iata: "LAX",
},
{
  id: 14,
  current_city: "Vancouver",
  destination_city: "Los Angeles",
  time: "10:30am-2:45pm",
  date: "December 14, 2023",
  airline: "American Airlines",
  price: "$465",
  iata: "LAX",
},
{
  id: 15,
  current_city: "Vancouver",
  destination_city: "Los Angeles",
  time: "3:30pm-7:00pm",
  date: "December 15, 2023",
  airline: "SouthWest",
  price: "$415",
  iata: "LAX",
},
{
  id: 16,
  current_city: "Vancouver",
  destination_city: "Los Angeles",
  time: "8:30pm-1:00am",
  date: "December 16, 2023",
  airline: "SouthWest",
  price: "$525",
  iata: "LAX",
},
{
  id: 17,
  current_city: "Vancouver",
  destination_city: "Honolulu",
  time: "3:30pm-8:00pm",
  date: "December 15, 2023",
  airline: "SouthWest",
  price: "$1180",
  iata: "HNL",
},
{
  id: 18,
  current_city: "Vancouver",
  destination_city: "Honolulu",
  time: "4:30am-10:45am",
  date: "December 17, 2023",
  airline: "American Airlines",
  price: "$1140",
  iata: "NHL",
},
{
  id: 19,
  current_city: "Vancouver",
  destination_city: "Honolulu",
  time: "11:30pm-5:00am",
  date: "December 12, 2023",
  airline: "SouthWest",
  price: "$960",
  iata: "NHL",
},
{
  id: 20,
  current_city: "Vancouver",
  destination_city: "Honolulu",
  time: "11:45pm-5:15am",
  date: "December 14, 2023",
  airline: "SouthWest",
  price: "$1110",
  iata: "NHL",
},
{
  id: 21,
  current_city: "Vancouver",
  destination_city: "Athens",
  time: "11:00am-8:30pm",
  date: "December 11, 2023",
  airline: "Air Canada",
  price: "$1350",
  iata: "ATH",
},
{
  id: 22,
  current_city: "Vancouver",
  destination_city: "Athens",
  time: "5:30am-1:45pm",
  date: "December 13, 2023",
  airline: "West Jet",
  price: "$1320",
  iata: "ATH",
},
{
  id: 23,
  current_city: "Vancouver",
  destination_city: "Athens",
  time: "3:30pm-11:50pm",
  date: "December 16, 2023",
  airline: "Lufthansa",
  price: "$1500",
  iata: "ATH",
},
{
  id: 24,
  current_city: "Vancouver",
  destination_city: "Athens",
  time: "5:30pm-1:50am",
  date: "December 16, 2023",
  airline: "Lufthansa",
  price: "$1500",
  iata: "ATH",
},
{
  id: 25,
  current_city: "Vancouver",
  destination_city: "Paris",
  time: "3:00pm-11:10pm",
  date: "December 18, 2023",
  airline: "Lufthansa",
  price: "$1680",
  iata: "CDG",
},
{
  id: 26,
  current_city: "Vancouver",
  destination_city: "Paris",
  time: "4:30am-12:20pm",
  date: "December 19, 2023",
  airline: "British Airlines",
  price: "$1750",
  iata: "CDG",
},
{
  id: 27,
  current_city: "Vancouver",
  destination_city: "Paris",
  time: "5:30pm-2:40am",
  date: "December 20, 2023",
  airline: "Air Canada",
  price: "$1800",
  iata: "CDG",
},
{
  id: 28,
  current_city: "Vancouver",
  destination_city: "Paris",
  time: "7:30pm-4:45am",
  date: "December 22, 2023",
  airline: "Air Canada",
  price: "$1880",
  iata: "CDG",
}
]



exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('flights_list').del()
  await knex('flights_list').insert(flightData)
};
